/* The Atlas — the manifesto as a living, zoomable map (Slice 1).
 * Spec: OD9-Discord-Bot/docs/MANIFESTO-ATLAS-SPEC.md
 * Data: inlined by atlas.php from scripts/web/data/manifesto-map.json
 *       (generated by tools/build_manifesto_map.py — never hand-edited).
 * Colors: resolved at runtime from od9.css custom properties (the
 *         founder-locked zone palette) — no hex copies in this file.
 * External file — NOT processed by the origin HTML minifier, so normal
 * comments are safe here (inline <script> in .php files: block comments only).
 */
(function () {
  "use strict";

  var dataEl = document.getElementById("atlas-data");
  if (!dataEl) return;
  var DATA;
  try { DATA = JSON.parse(dataEl.textContent); } catch (e) { return; }

  var canvas = document.getElementById("atlas-canvas");
  var stage = document.getElementById("atlas-stage");
  var card = document.getElementById("atlas-card");
  var liveChip = document.getElementById("atlas-live-chip");
  if (!canvas || !stage) return;
  var ctx = canvas.getContext("2d");

  var reducedMotion = window.matchMedia &&
    window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  /* ---- palette from od9.css tokens ---- */
  function token(name, fallback) {
    var v = getComputedStyle(document.documentElement).getPropertyValue(name);
    return (v && v.trim()) || fallback;
  }
  function rgba(hex, a) {
    var h = hex.replace("#", "");
    if (h.length === 3) h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
    var n = parseInt(h, 16);
    return "rgba(" + ((n >> 16) & 255) + "," + ((n >> 8) & 255) + "," +
      (n & 255) + "," + a + ")";
  }
  var C = {
    voidbg: token("--zone-void", "#0A0A0A"),
    cyan: token("--zone-cyan", "#00FFF7"),
    violet: token("--zone-violet", "#7A00FF"),
    gold: token("--gold", "#FFD700"),
    raw: token("--t-observer", "#8A9499"),
    forge: token("--t-pioneer", "#E5B53A"),
    chrome: token("--chrome", "#C0C0C0")
  };
  function stateColor(n) {
    if (n.state === "canon") return C.gold;
    if (n.state === "preached") return C.cyan;
    return C.raw;
  }

  /* ---- lookups ---- */
  var nodeById = {};
  var legacyToNode = {};
  DATA.nodes.forEach(function (n) {
    nodeById[n.id] = n;
    n.legacy.forEach(function (c) { legacyToNode[c] = n.id; });
  });
  var canonToNode = {};
  DATA.nodes.forEach(function (n) {
    (n.canon || []).forEach(function (c) { canonToNode[c.content_id] = n.id; });
  });
  var arcById = {};
  DATA.arcs.forEach(function (a) { arcById[a.id] = a; });

  /* ---- camera ---- */
  var W = DATA.world.w, H = DATA.world.h;
  var view = { w: 0, h: 0, dpr: 1 };
  var cam = { x: W / 2, y: H / 2, z: 1 };
  var target = { x: cam.x, y: cam.y, z: cam.z };
  var fitZ = 1;

  function resize() {
    var r = stage.getBoundingClientRect();
    view.w = Math.max(1, r.width);
    view.h = Math.max(1, r.height);
    view.dpr = Math.min(window.devicePixelRatio || 1, 2);
    canvas.width = Math.round(view.w * view.dpr);
    canvas.height = Math.round(view.h * view.dpr);
    canvas.style.width = view.w + "px";
    canvas.style.height = view.h + "px";
    fitZ = Math.min(view.w / W, view.h / H) * 0.95;
    target.z = clamp(target.z, fitZ * 0.85, 6);
    if (reducedMotion) snap();
  }
  function clamp(v, a, b) { return Math.max(a, Math.min(b, v)); }
  function toScreen(wx, wy) {
    return [(wx - cam.x) * cam.z + view.w / 2, (wy - cam.y) * cam.z + view.h / 2];
  }
  function toWorld(sx, sy) {
    return [(sx - view.w / 2) / cam.z + cam.x, (sy - view.h / 2) / cam.z + cam.y];
  }
  function snap() { cam.x = target.x; cam.y = target.y; cam.z = target.z; }

  /* ---- focus + card ---- */
  var focusedId = null, activeArc = null, liveNodeId = null;

  function esc(s) {
    return String(s).replace(/[&<>"']/g, function (ch) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[ch];
    });
  }
  var STATE_LABEL = { raw: "RAW — awaiting its forge", preached: "PREACHED",
    canon: "CANON — read it now" };

  /* What the object IS, in its own words — the astronomy, kept separate from
     what the chapter means. `real` is load-bearing, not decoration: anything
     proposed, hypothetical or fictional says so on its face, because half
     this set is engineering that has never been built. */
  function objectBlock(n, hideName) {
    var o = objectInfo(n);
    if (!o) return "";
    return '<div class="atlas-object">' +
      '<div class="atlas-object-head">' +
      (hideName ? "" :
        '<span class="atlas-object-name">' + esc(o.name) + "</span>") +
      '<span class="atlas-object-kind' + (o.real ? "" : " is-speculative") +
      '">' + esc(o.kind) + "</span></div>" +
      '<p class="atlas-object-blurb">' + esc(o.blurb) + "</p></div>";
  }

  function openBeyondCard(n) {
    if (!card) return;
    var o = objectInfo(n);
    var h = '<button class="atlas-card-close" id="atlas-card-close" aria-label="Close">&times;</button>';
    h += '<div class="atlas-card-eyebrow">Beyond Type 1</div>';
    h += "<h2>" + esc(o ? o.name : n.title) + "</h2>";
    h += '<div class="atlas-chips"><span class="atlas-chip atlas-chip-beyond">' +
      (o && o.real ? "OBSERVED" : "NOT BUILT") + "</span></div>";
    h += objectBlock(n, true);   /* the heading already IS the object name */
    h += '<p class="atlas-await">Past the last chapter. Volume 6 ends at ' +
      "&ldquo;Beyond Type 1&rdquo; &mdash; this is the shape of what that " +
      "means, drawn honestly: none of it exists yet.</p>";
    card.innerHTML = h;
    card.classList.add("open");
    var btn = document.getElementById("atlas-card-close");
    if (btn) btn.addEventListener("click", closeCard);
  }

  function openCard(n) {
    if (!card) return;
    if (n.beyond) { openBeyondCard(n); return; }
    var arcs = DATA.arcs.filter(function (a) {
      return a.route.indexOf(n.id) !== -1;
    });
    var h = "";
    h += '<button class="atlas-card-close" id="atlas-card-close" aria-label="Close">&times;</button>';
    h += '<div class="atlas-card-eyebrow">' +
      esc(n.num === "P" ? "Preface" : (n.num === "A" ? "Appendix" : "Chapter " + n.num)) +
      (n.tier ? ' · <span class="atlas-tier">' + esc(n.tier) + "</span>" : "") + "</div>";
    h += "<h2>" + esc(n.title) + "</h2>";
    h += '<div class="atlas-chips">';
    h += '<span class="atlas-chip atlas-chip-' + n.state + '">' + STATE_LABEL[n.state] + "</span>";
    if (n.forge) {
      var s = DATA.schedule && DATA.schedule[0];
      h += '<span class="atlas-chip atlas-chip-forge">IN THE FORGE' +
        (s ? " — Sermon " + esc(s.sermon) + " · " + esc(s.date) : "") + "</span>";
    }
    if (n.id === liveNodeId) h += '<span class="atlas-chip atlas-chip-live">&#9679; LIVE LESSON</span>';
    h += "</div>";
    if (n.legacy.length > 1) {
      h += '<p class="atlas-lineage">Forged from chapters ' +
        n.legacy.join(" · ") + " (structure decided 2026-08-20).</p>";
    }
    if (n.note) h += '<p class="atlas-note">' + esc(n.note) + "</p>";
    if (n.bullets && n.bullets.length) {
      h += "<ul>";
      n.bullets.forEach(function (b) { h += "<li>" + esc(b) + "</li>"; });
      h += "</ul>";
    }
    h += objectBlock(n);
    if (n.canon && n.canon.length) {
      h += '<div class="atlas-canon"><div class="atlas-canon-label">In the Codex:</div>';
      n.canon.forEach(function (c) {
        h += '<a class="atlas-canon-link" href="' + esc(c.url) + '">' +
          esc(c.title) + " &rarr;</a>";
      });
      h += "</div>";
    } else {
      h += '<p class="atlas-await">Awaiting its sermon — the live rewrites this map one Sunday at a time.</p>';
    }
    if (arcs.length) {
      h += '<p class="atlas-route">Route: ' + arcs.map(function (a) {
        return "Arc " + a.num + " — " + esc(a.name);
      }).join(" · ") + "</p>";
    }
    card.innerHTML = h;
    card.classList.add("open");
    var btn = document.getElementById("atlas-card-close");
    if (btn) btn.addEventListener("click", closeCard);
  }
  function closeCard() {
    if (card) card.classList.remove("open");
    focusedId = null;
    if (history.replaceState) history.replaceState(null, "", "#");
  }

  /* ---- codex reader host (same contract the board implements) ---- */
  var reader = document.getElementById("atlas-reader");
  var readerFrame = document.getElementById("atlas-reader-frame");
  function openLesson(url) {
    if (!reader || !readerFrame) { location.href = url; return; }
    readerFrame.src = url + (url.indexOf("?") === -1 ? "?embed=1" : "&embed=1");
    reader.removeAttribute("hidden");
  }
  /* the lesson's own "Done reading" CTA calls parent.__odClose() — closing
     returns the member to the map, never strands them in board-world */
  window.__odClose = function () {
    if (!reader) return;
    reader.setAttribute("hidden", "");
    if (readerFrame) readerFrame.src = "about:blank";
  };
  if (card) {
    card.addEventListener("click", function (e) {
      if (e.ctrlKey || e.metaKey || e.shiftKey || e.button === 1) return;
      var a = e.target && e.target.closest ? e.target.closest(".atlas-canon-link") : null;
      if (a) { e.preventDefault(); openLesson(a.getAttribute("href")); }
    });
  }

  function focusNode(id, withCard) {
    var n = nodeById[id];
    if (!n) return;
    focusedId = id;
    /* land PAST ZR_FULL so opening a chapter shows the object it resolves
       into — the old 2.1 sat just under the threshold and a click would
       have zoomed to a glow-dot and stopped there */
    target.x = n.x; target.y = n.y; target.z = Math.max(3.6, fitZ * 3);
    if (reducedMotion) snap();
    if (withCard !== false) openCard(n);
    if (history.replaceState) history.replaceState(null, "", "#" + id);
  }
  function fitRect(x, y, w, h) {
    target.x = x + w / 2; target.y = y + h / 2;
    target.z = clamp(Math.min(view.w / w, view.h / h) * 0.8, fitZ * 0.85, 6);
    if (reducedMotion) snap();
  }
  function fitAll() { fitRect(0, 0, W, H); activeArc = null; closeCard(); }

  function routeHash() {
    var raw = (location.hash || "").replace("#", "").toLowerCase();
    if (!raw) return;
    var m = raw.match(/^ch(\d+)$/);
    if (m) {
      var nid = legacyToNode[parseInt(m[1], 10)];
      if (nid) { focusNode(nid); return; }
    }
    if (nodeById[raw]) { focusNode(raw); return; }
    var v = raw.match(/^vol(\d)$/);
    if (v) {
      var vol = DATA.volumes.filter(function (x) {
        return x.vol === parseInt(v[1], 10);
      })[0];
      if (vol) { fitRect.apply(null, vol.region); return; }
    }
    if (arcById[raw]) {
      activeArc = raw;
      var pts = arcById[raw].route.map(function (id) { return nodeById[id]; });
      var xs = pts.map(function (p) { return p.x; });
      var ys = pts.map(function (p) { return p.y; });
      var minX = Math.min.apply(null, xs) - 80, maxX = Math.max.apply(null, xs) + 80;
      var minY = Math.min.apply(null, ys) - 80, maxY = Math.max.apply(null, ys) + 80;
      fitRect(minX, minY, maxX - minX, maxY - minY);
    }
  }

  /* ---- input ---- */
  var pointers = {}, dragging = false, downAt = null, pinchD = 0;
  canvas.addEventListener("pointerdown", function (e) {
    canvas.setPointerCapture(e.pointerId);
    pointers[e.pointerId] = [e.clientX, e.clientY];
    downAt = [e.clientX, e.clientY];
    dragging = false;
    var ks = Object.keys(pointers);
    if (ks.length === 2) {
      var a = pointers[ks[0]], b = pointers[ks[1]];
      pinchD = Math.hypot(a[0] - b[0], a[1] - b[1]);
    }
  });
  canvas.addEventListener("pointermove", function (e) {
    var prev = pointers[e.pointerId];
    if (!prev) {
      canvas.style.cursor = hitTest(e) ? "pointer" : "grab";
      return;
    }
    var ks = Object.keys(pointers);
    if (ks.length === 2) {
      pointers[e.pointerId] = [e.clientX, e.clientY];
      var a = pointers[ks[0]], b = pointers[ks[1]];
      var d = Math.hypot(a[0] - b[0], a[1] - b[1]);
      if (pinchD > 0) {
        target.z = clamp(target.z * (d / pinchD), fitZ * 0.85, 6);
        if (reducedMotion) snap();
      }
      pinchD = d;
      dragging = true;
      return;
    }
    var dx = e.clientX - prev[0], dy = e.clientY - prev[1];
    if (Math.abs(e.clientX - downAt[0]) + Math.abs(e.clientY - downAt[1]) > 6) dragging = true;
    if (dragging) {
      target.x -= dx / cam.z; target.y -= dy / cam.z;
      cam.x = target.x; cam.y = target.y;
    }
    pointers[e.pointerId] = [e.clientX, e.clientY];
  });
  function endPointer(e) {
    delete pointers[e.pointerId];
    pinchD = 0;
    if (!dragging && downAt) {
      var n = hitTest(e);
      if (n) focusNode(n.id);
      else closeCard();
    }
    dragging = false; downAt = null;
  }
  canvas.addEventListener("pointerup", endPointer);
  canvas.addEventListener("pointercancel", endPointer);
  canvas.addEventListener("wheel", function (e) {
    e.preventDefault();
    var f = Math.pow(1.0015, -e.deltaY);
    var before = toWorld(e.offsetX, e.offsetY);
    target.z = clamp(target.z * f, fitZ * 0.85, 6);
    cam.z = target.z;
    var after = toWorld(e.offsetX, e.offsetY);
    target.x += before[0] - after[0]; target.y += before[1] - after[1];
    cam.x = target.x; cam.y = target.y;
  }, { passive: false });
  document.addEventListener("keydown", function (e) {
    if (e.key !== "Escape") return;
    if (reader && !reader.hasAttribute("hidden")) { window.__odClose(); return; }
    closeCard();
  });

  function hitTest(e) {
    var rect = canvas.getBoundingClientRect();
    var p = toWorld(e.clientX - rect.left, e.clientY - rect.top);
    var best = null, bestD = 1e9;
    DATA.nodes.concat(BEYOND).forEach(function (n) {
      var d = Math.hypot(n.x - p[0], n.y - p[1]);
      if (d < bestD) { bestD = d; best = n; }
    });
    var r = Math.max(14, 11 / Math.sqrt(cam.z)) + 6;
    return bestD * cam.z < r * cam.z && bestD < 26 ? best : null;
  }

  /* ---- live beacon ---- */
  /* Relative URL: resolves under /od9/ locally and at the root on prod. */
  fetch("api/v1/atlas-live.php").then(function (r) {
    return r.ok ? r.json() : null;
  }).then(function (j) {
    if (!j || !j.designated) return;
    var nid = canonToNode[j.designated];
    if (!nid) return;
    liveNodeId = nid;
    if (liveChip) {
      var n = nodeById[nid];
      liveChip.textContent = "● LIVE LESSON — " +
        (n.num === "P" ? "PREFACE" : "CH " + n.legacy[0]);
      liveChip.classList.add("on");
      liveChip.addEventListener("click", function () { focusNode(nid); });
    }
    /* ?live=1 — the go-live announce's door: land on tonight's chapter.
       A #hash deep link wins if both are present. */
    if (/[?&]live=1/.test(location.search) && !location.hash) {
      focusNode(nid);
    }
  }).catch(function () { /* fail-open: no beacon */ });

  /* ---- the cosmos layer (founder direction 2026-08-21: constellation vibes —
     stars, not dots; nebulae, not boxes; constellation lines, not dashes).
     All procedural: seeded PRNG so the sky is identical every visit. ---- */
  function mulberry32(a) {
    return function () {
      a |= 0; a = a + 0x6D2B79F5 | 0;
      var t = Math.imul(a ^ a >>> 15, 1 | a);
      t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    };
  }
  var FIELD = [];
  (function seedField() {
    var rnd = mulberry32(3369); /* OD9's sky, same every visit */
    var layers = [
      { n: 130, p: 0.18, rMax: 1.1, aMax: 0.5 },
      { n: 90, p: 0.42, rMax: 1.5, aMax: 0.7 },
      { n: 45, p: 0.75, rMax: 2.1, aMax: 0.95 }
    ];
    layers.forEach(function (L) {
      for (var i = 0; i < L.n; i++) {
        var tint = rnd();
        FIELD.push({
          x: rnd() * (W + 800) - 400, y: rnd() * (H + 800) - 400,
          p: L.p, r: 0.4 + rnd() * L.rMax, a: 0.12 + rnd() * L.aMax,
          ph: rnd() * 6.28, sp: 0.4 + rnd() * 1.2,
          c: tint < 0.72 ? "#FFFFFF" : (tint < 0.88 ? C.cyan : C.violet)
        });
      }
    });
  })();
  var NEBULAE = [];
  (function seedNebulae() {
    var rnd = mulberry32(909);
    DATA.volumes.forEach(function (v) {
      var r = v.region;
      var blobs = 2 + Math.round(rnd());
      for (var i = 0; i < blobs; i++) {
        NEBULAE.push({
          vol: v.vol,
          x: r[0] + r[2] * (0.2 + rnd() * 0.6),
          y: r[1] + r[3] * (0.2 + rnd() * 0.6),
          rad: Math.max(r[2], r[3]) * (0.3 + rnd() * 0.35),
          c: rnd() < 0.7 ? C.violet : C.cyan,
          a: 0.05 + rnd() * 0.05,
          /* ambient-motion phase (2026-08-27): seeded, so each wash breathes
             and drifts on its own slow cycle but identically every visit */
          ph: rnd() * 6.28
        });
      }
    });
  })();

  /* founder-generated nebula plates (Flow, 2026-08-21) — one per volume,
     pre-feathered to alpha by tools/build_atlas_plates.py. Fail-open: until a
     plate loads, that volume keeps its procedural nebulae. */
  var PLATES = {};
  (function loadPlates() {
    var pv = (stage.getAttribute("data-plates-v") || "1");
    var keys = { 0: "preface", 1: "vol1", 2: "vol2", 3: "vol3", 4: "vol4", 5: "vol5", 6: "vol6" };
    DATA.volumes.forEach(function (v) {
      var img = new Image();
      img.onload = function () { PLATES[v.vol] = img; };
      img.src = "images/atlas/plates/" + keys[v.vol] + ".webp?v=" + pv;
    });
  })();
  function drawStarGlow(x, y, r, color, coreAlpha) {
    var g = ctx.createRadialGradient(x, y, 0, x, y, r);
    g.addColorStop(0, rgba("#FFFFFF", coreAlpha));
    g.addColorStop(0.25, rgba(color, coreAlpha * 0.85));
    g.addColorStop(1, rgba(color, 0));
    ctx.fillStyle = g;
    ctx.beginPath(); ctx.arc(x, y, r, 0, 7); ctx.fill();
  }
  function drawFlare(x, y, len, color, alpha) {
    ctx.strokeStyle = rgba(color, alpha);
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(x - len, y); ctx.lineTo(x + len, y);
    ctx.moveTo(x, y - len); ctx.lineTo(x, y + len);
    ctx.stroke();
  }

  /* ---- ambient motion: shooting stars (2026-08-27) --------------------------
     The LAYOUT of the sky is deterministic (seeded) — that's the identity.
     Ephemeral events are allowed to be random: a meteor every ~15-40s, one at
     a time, screen-space (atmosphere, not geography), gone in under a second.
     Disabled entirely under prefers-reduced-motion. rAF pausing in hidden tabs
     means no meteor debt accumulates while the tab is backgrounded. */
  /* ?meteorfast — debug cadence so the layer is DETERMINISTICALLY testable
     against the real file (a 0.7s streak every ~25s defeats statistical
     screenshot sampling; an untestable ambient feature would be trusted on
     faith forever). Production cadence is the default. */
  var meteorFast = /[?&]meteorfast/.test(location.search);
  var meteor = null;
  var nextMeteorAt = Date.now() +
    (meteorFast ? 700 : 6000 + Math.random() * 10000);
  function meteorGap() {
    return meteorFast ? 1500 + Math.random() * 1500
                      : 15000 + Math.random() * 25000;
  }
  function spawnMeteor(nowAbs) {
    var edge = Math.random();
    var x0 = view.w * (0.1 + Math.random() * 0.8);
    var y0 = view.h * (edge < 0.5 ? 0.05 + Math.random() * 0.2 : 0.25 + Math.random() * 0.3);
    var ang = (35 + Math.random() * 25) * Math.PI / 180 * (Math.random() < 0.5 ? 1 : -1);
    meteor = { x: x0, y: y0, dx: Math.cos(ang), dy: Math.abs(Math.sin(ang)),
               start: nowAbs, life: 650 + Math.random() * 350,
               speed: 0.55 + Math.random() * 0.35 };
  }
  function drawMeteor(nowAbs) {
    if (reducedMotion) return;
    if (!meteor) {
      if (nowAbs >= nextMeteorAt) spawnMeteor(nowAbs);
      return;
    }
    var t = (nowAbs - meteor.start) / meteor.life;
    if (t >= 1) {
      meteor = null;
      nextMeteorAt = nowAbs + meteorGap();
      return;
    }
    var dist = meteor.speed * (nowAbs - meteor.start);
    var hx = meteor.x + meteor.dx * dist, hy = meteor.y + meteor.dy * dist;
    var tail = 110 * (1 - t * 0.35);
    var fade = t < 0.15 ? t / 0.15 : (1 - t);
    /* ADDITIVE blending + a glowing head (2026-08-27): the first cut was a
       1.4px source-over gradient line — console probes proved it drew every
       frame while pixel diffs proved nobody could see it: white at 0.85α
       composited over the bright Flow plates is a near-zero delta. 'lighter'
       ADDS light, so the streak reads over the void AND over a gold nebula. */
    ctx.globalCompositeOperation = "lighter";
    var g = ctx.createLinearGradient(hx, hy, hx - meteor.dx * tail, hy - meteor.dy * tail);
    g.addColorStop(0, rgba("#FFFFFF", 0.9 * fade));
    g.addColorStop(0.35, rgba(C.cyan, 0.5 * fade));
    g.addColorStop(1, rgba(C.cyan, 0));
    ctx.strokeStyle = g;
    ctx.lineWidth = 2.1;
    ctx.beginPath();
    ctx.moveTo(hx, hy);
    ctx.lineTo(hx - meteor.dx * tail, hy - meteor.dy * tail);
    ctx.stroke();
    drawStarGlow(hx, hy, 7, C.cyan, 0.9 * fade);
    ctx.globalCompositeOperation = "source-over";
  }

  /* ---- render ---- */
  var t0 = Date.now();
  /* ---- zoom-resolve (Slice 2.5): chapters become real objects ----------
     Push past ZR_IN and a glow-dot crossfades into the object that encodes
     what the chapter IS. The mapping is semantic and deliberately layered:
     IDENTITY (this specific chapter) beats VOLUME beats STATE, because the
     state is already carried by the glow ring that persists around the
     object — a preached black-hole-star keeps its cyan ring, it does not
     turn into a pulsar. Sprites are built by tools/build_atlas_sprites.py;
     anything missing simply never draws, leaving today's glow-dot render
     (fail-open, same contract as the nebula plates). */
  var ZR_IN = 2.0, ZR_FULL = 3.2, SPRITE_K = 12.0;
  /* The spec called for "screen" (black vanishes, luminance survives). That
     is the right instinct for a sprite drawn on black over a black void, but
     the volume plates are NOT black -- measured over the gold Volume 1 plate,
     screen-blending ch5 was invisible. With the dark pocket below doing the
     "black vanishes" job structurally, source-over reproduces the founder's
     masters faithfully, dark engineered hulls included, instead of erasing
     every unlit surface. ?spriteblend=screen|lighter to compare live. */
  var SPRITE_BLEND = (/[?&]spriteblend=([\w-]+)/.exec(location.search) || [])[1]
    || "source-over";
  /* The registry — what each object IS and which chapter it lands on — is
     data, written by tools/build_atlas_sprites.py from tools/atlas_objects.py
     and inlined by atlas.php. This file deliberately keeps NO copy: adding an
     object is a registry edit plus a generation, never a code change, and the
     two can't drift. No registry => every lookup returns null => plain
     glow-dots, which is exactly the pre-object render. */
  var OBJ = (function () {
    var el = document.getElementById("atlas-objects");
    if (!el) return null;
    try { return JSON.parse(el.textContent); } catch (e) { return null; }
  })();
  var spriteCache = {};
  var spriteV = (stage.getAttribute("data-sprites-v") || "1");

  function spriteKeyFor(n) {
    if (!OBJ) return null;
    if (n.beyond) return n.sprite;
    if (OBJ.byChapter[n.id]) return OBJ.byChapter[n.id];
    var v = OBJ.byVolume[String(n.vol)];
    if (v) return v;                        /* the movement leaves the system */
    if (n.forge && OBJ.byState.forge) return OBJ.byState.forge;
    return OBJ.byState[n.state] || OBJ.byState.raw || null;
  }
  function objectInfo(n) {
    var k = spriteKeyFor(n);
    return (k && OBJ && OBJ.objects[k]) || null;
  }

  /* ---- the beyond-Type-1 field ----------------------------------------
     Volume 6 closes on ch67, "Beyond Type 1 — Ultimate Potential", and out
     past the map's right edge is what beyond looks like: structures that
     move or enclose a whole star. They are not chapters — no number, no
     state, no codex — so they carry a violet speculative ring instead of a
     state ring, and their card says plainly what is proposal and what is
     fiction. Made of the same pseudo-node shape as a chapter so focus,
     hit-testing and deep links all work without a second code path. */
  var BEYOND = ((OBJ && OBJ.beyond) || []).map(function (b) {
    var info = (OBJ.objects && OBJ.objects[b.sprite]) || {};
    return {
      id: b.id, x: b.x, y: b.y, sprite: b.sprite, beyond: true,
      num: "", state: "beyond", legacy: [], canon: [],
      title: info.name || b.sprite
    };
  });
  BEYOND.forEach(function (b) { nodeById[b.id] = b; });

  /* Draws one resolved object, centred, at radius `orb`, fading in with
     `alpha`. Chapters and the beyond-Type-1 field both come through here so
     there is exactly one implementation of the compositing.

     A WELL OF SPACE goes down first. The masters were generated on pure
     black, and a volume plate is anything but: screen-blending ch5's red
     sphere straight onto the gold Volume 1 nebula added almost nothing a
     viewer could see. Sinking a soft dark pocket restores the contrast the
     art was drawn for, whatever it happens to be flying over — and reads as
     depth, the object being nearer the camera than the cloud behind it. */
  function drawObject(sx, sy, orb, alpha, key) {
    if (!key) return false;
    var img = spriteImage(key);
    if (!img) return false;
    var pr = orb * 1.32;
    var pk = ctx.createRadialGradient(sx, sy, orb * 0.1, sx, sy, pr);
    pk.addColorStop(0, rgba("#000000", 0.9 * alpha));
    pk.addColorStop(0.6, rgba("#000000", 0.82 * alpha));
    pk.addColorStop(1, rgba("#000000", 0));
    ctx.fillStyle = pk;
    ctx.beginPath(); ctx.arc(sx, sy, pr, 0, 7); ctx.fill();

    ctx.globalCompositeOperation = SPRITE_BLEND;
    ctx.globalAlpha = alpha;
    ctx.drawImage(img, sx - orb, sy - orb, orb * 2, orb * 2);
    ctx.globalAlpha = 1;
    ctx.globalCompositeOperation = "source-over";
    return true;
  }

  function spriteImage(key) {
    var s = spriteCache[key];
    if (s === undefined) {
      spriteCache[key] = "loading";
      var img = new Image();
      img.onload = function () { spriteCache[key] = img; };
      img.onerror = function () { spriteCache[key] = "failed"; };
      img.src = "images/atlas/sprites/" + key + ".webp?v=" + spriteV;
      return null;
    }
    return (s === "loading" || s === "failed") ? null : s;
  }

  function draw() {
    if (!reducedMotion) {
      cam.x += (target.x - cam.x) * 0.14;
      cam.y += (target.y - cam.y) * 0.14;
      cam.z += (target.z - cam.z) * 0.14;
    } else { snap(); }
    ctx.setTransform(view.dpr, 0, 0, view.dpr, 0, 0);
    ctx.fillStyle = C.voidbg;
    ctx.fillRect(0, 0, view.w, view.h);

    var z = cam.z;
    var now = Date.now() - t0;
    var pulse = reducedMotion ? 0.6 : 0.35 + 0.3 * Math.sin(now / 550);

    /* deep field — parallax stars behind everything */
    for (var fi = 0; fi < FIELD.length; fi++) {
      var st = FIELD[fi];
      /* parallax: each layer tracks the camera at a fraction of full depth */
      var sx = view.w / 2 + (st.x - W / 2 - (cam.x - W / 2) * st.p) * z * 0.9;
      var sy = view.h / 2 + (st.y - H / 2 - (cam.y - H / 2) * st.p) * z * 0.9;
      if (sx < -8 || sy < -8 || sx > view.w + 8 || sy > view.h + 8) continue;
      var tw = reducedMotion ? 1 : 0.72 + 0.28 * Math.sin(now / 900 * st.sp + st.ph);
      ctx.fillStyle = rgba(st.c, st.a * tw);
      ctx.beginPath(); ctx.arc(sx, sy, st.r * Math.min(z, 1.6), 0, 7); ctx.fill();
    }

    /* volume nebulae — the founder's Flow plates where loaded; procedural
       washes only for volumes whose plate hasn't arrived (fail-open).
       BREATHING (2026-08-27): each volume inhales on its own ~9s cycle,
       phase-offset per volume so the map never pulses in unison. Depth is
       ±0.04 alpha — felt, not seen. Static under reduced motion. */
    DATA.volumes.forEach(function (v) {
      var p = PLATES[v.vol];
      if (!p) return;
      var r = v.region;
      var p0 = toScreen(r[0], r[1]), p1 = toScreen(r[0] + r[2], r[1] + r[3]);
      if (p1[0] < 0 || p1[1] < 0 || p0[0] > view.w || p0[1] > view.h) return;
      ctx.globalAlpha = reducedMotion ? 0.92
        : 0.92 + 0.04 * Math.sin(now / 9000 + v.vol * 1.7);
      ctx.drawImage(p, p0[0], p0[1], p1[0] - p0[0], p1[1] - p0[1]);
      ctx.globalAlpha = 1;
    });
    NEBULAE.forEach(function (nb) {
      if (PLATES[nb.vol]) return;
      /* slow drift + breath for the procedural washes (world-space ±3u) */
      var nbx = nb.x, nby = nb.y, nba = nb.a;
      if (!reducedMotion) {
        nbx += 3 * Math.sin(now / 17000 + nb.ph);
        nby += 3 * Math.cos(now / 23000 + nb.ph);
        nba *= 1 + 0.22 * Math.sin(now / 11000 + nb.ph);
      }
      var s = toScreen(nbx, nby);
      var rad = nb.rad * z;
      if (s[0] + rad < 0 || s[1] + rad < 0 || s[0] - rad > view.w || s[1] - rad > view.h) return;
      var g = ctx.createRadialGradient(s[0], s[1], 0, s[0], s[1], rad);
      g.addColorStop(0, rgba(nb.c, nba));
      g.addColorStop(1, rgba(nb.c, 0));
      ctx.fillStyle = g;
      ctx.beginPath(); ctx.arc(s[0], s[1], rad, 0, 7); ctx.fill();
    });

    /* shooting star — atmosphere IN FRONT of the nebula backdrop, behind the
       map's structural layers. First cut drew it under the plates "for depth
       correctness" and the meteor hunt proved it invisible: the plates are
       near-opaque images covering most of the sky. Verified by pixel-diff
       sampling after the move. */
    drawMeteor(Date.now());

    /* faint volume boundaries + labels (legibility layer over the nebulae) */
    DATA.volumes.forEach(function (v) {
      var r = v.region;
      var p0 = toScreen(r[0], r[1]), p1 = toScreen(r[0] + r[2], r[1] + r[3]);
      ctx.strokeStyle = rgba(C.violet, 0.16);
      ctx.lineWidth = 1;
      roundRect(p0[0], p0[1], p1[0] - p0[0], p1[1] - p0[1], 14 * Math.min(z, 1.4));
      ctx.stroke();
      ctx.fillStyle = rgba(C.chrome, z < 1.6 ? 0.7 : 0.3);
      ctx.font = "600 " + clamp(12 * z, 10, 20) + "px Rajdhani, sans-serif";
      ctx.textAlign = "left"; ctx.textBaseline = "top";
      ctx.fillText(v.name.toUpperCase(), p0[0] + 10, p0[1] + 8);
      if (z >= 0.9) {
        ctx.fillStyle = rgba(C.chrome, 0.35);
        ctx.font = clamp(9 * z, 8, 13) + "px 'Exo 2', sans-serif";
        ctx.fillText(v.sub, p0[0] + 10, p0[1] + 10 + clamp(13 * z, 11, 21));
      }
    });

    /* constellation lines — thin, glowing, drawn under the stars */
    DATA.arcs.forEach(function (a) {
      var on = activeArc === a.id;
      var pass;
      for (pass = 0; pass < 2; pass++) {
        ctx.strokeStyle = rgba(pass === 0 ? C.violet : (on ? C.cyan : C.violet),
          pass === 0 ? (on ? 0.35 : 0.18) : (on ? 0.95 : 0.5));
        ctx.lineWidth = pass === 0 ? (on ? 5 : 3.5) : (on ? 1.4 : 0.8);
        ctx.beginPath();
        a.route.forEach(function (id, i) {
          var n = nodeById[id];
          var s = toScreen(n.x, n.y);
          if (i === 0) ctx.moveTo(s[0], s[1]); else ctx.lineTo(s[0], s[1]);
        });
        ctx.stroke();
      }
      /* energy flowing along the SELECTED arc (2026-08-27): moving dashes in
         route order — the reading direction made visible. Selected-arc only
         (all arcs shimmering would be noise), skipped under reduced motion
         where the solid bright line above already marks the selection. */
      if (on && !reducedMotion) {
        ctx.setLineDash([5, 17]);
        ctx.lineDashOffset = -(now / 28) % 22;
        ctx.strokeStyle = rgba("#FFFFFF", 0.7);
        ctx.lineWidth = 1.6;
        ctx.beginPath();
        a.route.forEach(function (id, i) {
          var n = nodeById[id];
          var s = toScreen(n.x, n.y);
          if (i === 0) ctx.moveTo(s[0], s[1]); else ctx.lineTo(s[0], s[1]);
        });
        ctx.stroke();
        ctx.setLineDash([]);
      }
    });

    /* chapter stars */
    var r = Math.max(5, Math.min(11, 6.5 * Math.sqrt(z)));
    /* how far the zoom-resolve has come: 0 = pure glow, 1 = full object */
    var zres = clamp((z - ZR_IN) / (ZR_FULL - ZR_IN), 0, 1);
    DATA.nodes.forEach(function (n) {
      var s = toScreen(n.x, n.y);
      if (s[0] < -80 || s[1] < -80 || s[0] > view.w + 80 || s[1] > view.h + 80) return;
      var col = stateColor(n);
      var tw = reducedMotion ? 1 : 0.85 + 0.15 * Math.sin(now / 700 + n.x);
      if (n.forge || n.id === liveNodeId) {
        drawStarGlow(s[0], s[1], r * 4.2 + (reducedMotion ? 0 : pulse * 6), C.forge, 0.5 * pulse + 0.25);
        drawFlare(s[0], s[1], r * (3.2 + (reducedMotion ? 0 : pulse * 1.5)), C.forge, 0.5);
      }
      /* LIVE beacon ripple (2026-08-27): forge nodes BREATHE (work being
         done); the live node EMITS — two expanding rings, half a period
         apart, like a signal going out. Distinct semantics, distinct motion.
         Reduced motion: one static ring still marks it as live. */
      if (n.id === liveNodeId) {
        if (reducedMotion) {
          ctx.strokeStyle = rgba(C.cyan, 0.55); ctx.lineWidth = 1.2;
          ctx.beginPath(); ctx.arc(s[0], s[1], r * 3.0, 0, 7); ctx.stroke();
        } else {
          for (var ri = 0; ri < 2; ri++) {
            var rp = ((now / 1800) + ri * 0.5) % 1;
            ctx.strokeStyle = rgba(C.cyan, 0.55 * (1 - rp));
            ctx.lineWidth = 1.6 * (1 - rp * 0.6);
            ctx.beginPath();
            ctx.arc(s[0], s[1], r * (1.6 + rp * 4.6), 0, 7);
            ctx.stroke();
          }
        }
      }
      /* the glow dims as the object takes over — but STATE never stops being
         visible: what fades out as a glow fades back in as a ring drawn at
         the object's own perimeter (see below), so a raw chapter still reads
         raw when it's a 300px telescope. */
      var gd = 1 - zres * 0.72;
      if (n.state === "canon") {
        drawStarGlow(s[0], s[1], r * 3.4, col, 0.85 * tw * gd);
        drawFlare(s[0], s[1], r * 2.6 * tw, col, 0.55 * tw * gd);
      } else if (n.state === "preached") {
        drawStarGlow(s[0], s[1], r * 2.8, col, 0.75 * tw * gd);
      } else {
        drawStarGlow(s[0], s[1], r * 1.7, col, 0.4 * tw * gd);
      }
      /* object diameter — grows with zoom so pushing in feels like approach */
      var d = r * SPRITE_K * (z / ZR_IN);
      var orb = d * 0.5;                       /* the object's own radius */
      if (zres > 0) {
        drawObject(s[0], s[1], orb, zres, spriteKeyFor(n));
        /* state ring AROUND the object */
        ctx.strokeStyle = rgba(col, 0.4 * zres * tw);
        ctx.lineWidth = Math.max(1, 1.8 * zres);
        ctx.beginPath(); ctx.arc(s[0], s[1], orb * 0.92, 0, 7); ctx.stroke();
      }
      /* stellar core — the object's own light replaces it once resolved */
      if (zres < 1) {
        ctx.fillStyle = rgba("#FFFFFF",
          (n.state === "raw" ? 0.55 : 0.95) * (1 - zres));
        ctx.beginPath(); ctx.arc(s[0], s[1], Math.max(1.4, r * 0.38), 0, 7); ctx.fill();
      }
      if (focusedId === n.id) {
        ctx.strokeStyle = rgba(C.cyan, 0.9); ctx.lineWidth = 1.4;
        ctx.beginPath();
        ctx.arc(s[0], s[1], (zres > 0 ? orb * 0.92 : r) + 4, 0, 7);
        ctx.stroke();
      }
      /* labels clear the object once it resolves, instead of sitting on it */
      var labelY = s[1] + (zres > 0 ? orb * 0.92 : r) + 4;
      if (z >= 0.85) {
        ctx.fillStyle = rgba(C.chrome, 0.9);
        ctx.font = "600 " + clamp(8.5 * z, 9, 15) + "px Rajdhani, sans-serif";
        ctx.textAlign = "center"; ctx.textBaseline = "top";
        ctx.fillText(n.num, s[0], labelY);
      }
      if (z >= 1.6) {
        ctx.fillStyle = rgba(C.chrome, 0.65);
        ctx.font = clamp(5.5 * z, 9, 14) + "px 'Exo 2', sans-serif";
        var t = n.title.length > 30 ? n.title.slice(0, 29) + "…" : n.title;
        ctx.fillText(t, s[0], labelY + 2 + clamp(9 * z, 10, 16));
      }
    });
    drawBeyondField(z, now, zres);
    requestAnimationFrame(draw);
  }

  function drawBeyondField(z, now, zres) {
    if (!BEYOND.length) return;
    /* the trail: ch67 literally points the way out of the map */
    var from = nodeById[OBJ.beyondTrailFrom];
    var to = nodeById[OBJ.beyondTrailTo];
    if (from && to) {
      var a = toScreen(from.x, from.y);
      var b0 = toScreen(to.x, to.y);
      ctx.save();
      ctx.setLineDash([3, 12]);
      if (!reducedMotion) ctx.lineDashOffset = -(now / 90) % 15;
      ctx.strokeStyle = rgba(C.violet, 0.3);
      ctx.lineWidth = 1;
      ctx.beginPath(); ctx.moveTo(a[0], a[1]); ctx.lineTo(b0[0], b0[1]);
      ctx.stroke();
      ctx.restore();
    }
    /* field label, sized like a volume label so it reads as a region */
    var lab = toScreen(OBJ.beyondLabelAt[0], OBJ.beyondLabelAt[1]);
    if (lab[0] < view.w + 300 && lab[0] > -400) {
      ctx.fillStyle = rgba(C.violet, 0.75);
      ctx.font = "600 " + clamp(11 * z, 10, 19) + "px Rajdhani, sans-serif";
      ctx.textAlign = "left"; ctx.textBaseline = "top";
      ctx.fillText(OBJ.beyondLabel, lab[0], lab[1]);
      ctx.fillStyle = rgba(C.raw, 0.5);
      ctx.font = clamp(7 * z, 9, 13) + "px 'Exo 2', sans-serif";
      ctx.fillText("what a civilisation builds after a planet",
        lab[0], lab[1] + clamp(13 * z, 13, 22));
    }
    var r = Math.max(5, Math.min(11, 6.5 * Math.sqrt(z)));
    BEYOND.forEach(function (b) {
      var s = toScreen(b.x, b.y);
      if (s[0] < -140 || s[1] < -140 || s[0] > view.w + 140 || s[1] > view.h + 140) return;
      var tw = reducedMotion ? 1 : 0.8 + 0.2 * Math.sin(now / 1100 + b.x);
      var orb = r * SPRITE_K * (z / ZR_IN) * 0.5;
      /* dimmer than a chapter at distance — these are hints, not the map */
      drawStarGlow(s[0], s[1], r * 1.5, C.violet, 0.34 * tw * (1 - zres * 0.72));
      if (zres > 0) {
        drawObject(s[0], s[1], orb, zres, b.sprite);
        ctx.save();
        ctx.setLineDash([2, 6]);          /* dashed = speculative, not state */
        ctx.strokeStyle = rgba(C.violet, 0.45 * zres * tw);
        ctx.lineWidth = Math.max(1, 1.6 * zres);
        ctx.beginPath(); ctx.arc(s[0], s[1], orb * 0.92, 0, 7); ctx.stroke();
        ctx.restore();
      }
      if (zres < 1) {
        ctx.fillStyle = rgba("#FFFFFF", 0.4 * (1 - zres));
        ctx.beginPath(); ctx.arc(s[0], s[1], Math.max(1.2, r * 0.3), 0, 7); ctx.fill();
      }
      if (focusedId === b.id) {
        ctx.strokeStyle = rgba(C.cyan, 0.9); ctx.lineWidth = 1.4;
        ctx.beginPath();
        ctx.arc(s[0], s[1], (zres > 0 ? orb * 0.92 : r) + 4, 0, 7);
        ctx.stroke();
      }
      if (z >= 1.2) {
        ctx.fillStyle = rgba(C.chrome, 0.62);
        ctx.font = clamp(6 * z, 9, 14) + "px 'Exo 2', sans-serif";
        ctx.textAlign = "center"; ctx.textBaseline = "top";
        ctx.fillText(b.title, s[0], s[1] + (zres > 0 ? orb * 0.92 : r) + 5);
      }
    });
  }

  function roundRect(x, y, w, h, rad) {
    rad = Math.min(rad, w / 2, h / 2);
    ctx.beginPath();
    ctx.moveTo(x + rad, y);
    ctx.arcTo(x + w, y, x + w, y + h, rad);
    ctx.arcTo(x + w, y + h, x, y + h, rad);
    ctx.arcTo(x, y + h, x, y, rad);
    ctx.arcTo(x, y, x + w, y, rad);
    ctx.closePath();
  }

  /* ---- controls ---- */
  var zi = document.getElementById("atlas-zoom-in");
  var zo = document.getElementById("atlas-zoom-out");
  var zr = document.getElementById("atlas-zoom-reset");
  if (zi) zi.addEventListener("click", function () {
    target.z = clamp(target.z * 1.45, fitZ * 0.85, 6); if (reducedMotion) snap();
  });
  if (zo) zo.addEventListener("click", function () {
    target.z = clamp(target.z / 1.45, fitZ * 0.85, 6); if (reducedMotion) snap();
  });
  if (zr) zr.addEventListener("click", fitAll);

  window.addEventListener("resize", resize);
  window.addEventListener("hashchange", routeHash);

  resize();
  cam.z = target.z = fitZ; snap();
  /* ?og=1 — share-card capture: exact frame on the canon constellation
     (no fit margin; V5/V6 labels stay just out of the bottom edge) */
  if (/[?&]og=1/.test(location.search)) {
    target.x = 555; target.y = 292;
    target.z = Math.min(view.w / 1130, view.h / 595);
    snap();
  } else {
    routeHash();
  }
  requestAnimationFrame(draw);
})();
